### ISSUE TITLE
error hehe

### ISSUE THREAD

**Issue by fadhil-riyanto** [Yonle/openradiobot#1]
node:events:342
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND r2---sn-uigxxi0ujipnvo-ngbs.googlevideo.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26)
Emitted 'error' event on PassThrough instance at:
    at PassThrough.<anonymous> (C:\BALI64\openradiobot\node_modules\openradio\core\index.js:38:45)
    at PassThrough.emit (node:events:377:35)
    at PassThrough.emit (node:events:365:28)
    at ClientRequest.onError (C:\BALI64\openradiobot\node_modules\miniget\dist\index.js:152:24)
    at ClientRequest.emit (node:events:365:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:365:28)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'r2---sn-uigxxi0ujipnvo-ngbs.googlevideo.com'
}

**Comment by Yonle** [comment]
Google are u okeh?

**Comment by fadhil-riyanto** [comment]
Gw ga paham node ::)
Ga bisa benerin. Paham js cuma segelintir. Selebihnya ga bisa wkaka
